import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import Popover from 'antd/es/popover';
import Button from 'antd/es/button';
import Carousel from 'antd/es/carousel';
import registerServiceWorker from './registerServiceWorker';
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
